# Generated by Django 3.0.5 on 2021-01-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
