# Generated by Django 3.0.5 on 2021-01-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210109_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='title'),
        ),
    ]
