# Generated by Django 3.1.5 on 2021-01-21 04:25

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage('D:\\Projects\\github\\TravTogether_Backend\\backend\\../static\\media'), upload_to=user.models.upload_to, verbose_name='profilePicture'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
