# Generated by Django 3.0.5 on 2020-12-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fromFirebase',
            field=models.BooleanField(default=False, verbose_name='fromFirebase'),
        ),
    ]
