# Generated by Django 3.1.5 on 2021-01-21 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210120_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=1, max_length=100, verbose_name='sender'),
            preserve_default=False,
        ),
    ]
