# Generated by Django 3.1.5 on 2021-01-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210120_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='subject',
        ),
    ]
